name: BedrockBreaker
main: com.example.bedrockbreaker.BedrockBreaker
version: 1.0
api-version: 1.16
commands:
  bedrockbreaker:
    description: 破坏准星所指向的基岩
    usage: /<command>
    aliases: [breakbr]
    permission: bedrockbreaker.break
permissions:
  bedrockbreaker.break:
    description: 允许玩家使用破坏基岩的命令
    default: op
